DELIMITER $$
CREATE FUNCTION calcularEdad(fecha_nac DATE)
RETURNS INT
DETERMINISTIC
BEGIN
  RETURN TIMESTAMPDIFF(YEAR, fecha_nac, CURDATE());
END$$
DELIMITER ;


DELIMITER $$
CREATE FUNCTION totalHorasEmpleado(idEmp INT)
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
  DECLARE total DECIMAL(10,2);
  SELECT SUM(horas_extra) INTO total FROM Asistencia WHERE ID_empleado = idEmp;
  RETURN total;
END$$
DELIMITER ;
